version: ""

formatter: markdown table

name: terraform-aws-limits-monitor

content: |-
  # AWS Limit Monitor

  Terraform module to deploy the [AWS Limit Monitor Solution](https://github.com/aws-solutions/aws-limit-monitor) for monitoring AWS service limits. It monitors limits across services supported by Amazon Trusted Advisor; in multiple regions and multiple AWS accounts. The solution integrates with Amazon SNS and Slack to notify customers for service limits approaching thresholds.

  [Documentation](https://aws.amazon.com/solutions/implementations/limit-monitor/)

  # Example - Email
  ```hcl
  {{ include "examples/example_email.tfnot" }}
  ```

  # Example - Email
  ```hcl
  {{ include "examples/example_slack.tfnot" }}
  ```

  ---

  {{ .Requirements }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  ---

  ## Contributors
  - Borja Lopez [StratusChris](https://github.com/borjalopez-sg)
  - Wesley Kirkland [wesleykirklandsg](https://github.com/wesleykirklandsg)

  Note, manual changes to the README will be overwritten when the documentation is updated. To update the documentation, run `terraform-docs -c .config/.terraform-docs.yml .`

sections:
  show:
    - requirements
    - resources
    - inputs
    - outputs

sort:
  enabled: true
  by: name

output:
  file: README.md
  mode: replace
